version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-node-browsers

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: run tests
          command: bundle exec rspec

      - run:
          name: run lint
          command: bundle exec rubocop
